version: '3'

services:
  familydb:
    container_name: familydb
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=familydb
    expose:
      - 3306
    networks:
      - backdb
    restart: always

  family-organiser-backend:
    container_name: family-organiser-backend
    image: family-organiser-backend:latest
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8050:8050
    depends_on:
      - familydb
    networks:
      - backdb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://familydb:3306/familydb





volumes:
  mariadb:


networks:
  backdb:
    driver: bridge