name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
          
      - name: Docker Setup Buildx
        # You may pin to the exact commit or the version.
        # uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25
        uses: docker/setup-buildx-action@v1.6.0
        
    
      - name: action-docker-compose
        # You may pin to the exact commit or the version.
        # uses: sudo-bot/action-docker-compose@cd01e23bd7a852c4c419d8cb4bcdaa324b5de819
        uses: sudo-bot/action-docker-compose@latest
        with:
         cli-args: up -d

    


      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify clean install
